### ISSUE TITLE
blueprints of infinity logistic chests only store "infinity filters"-tab

### ISSUE THREAD

**Issue by Calibretto22** [raiguard/InfinityMode#19] opened 2019-11-10 14:57 UTC
When creating blueprints of infinity logistic chests (**storage, buffer & requester**) the blueprint only saves the  configuration of the infinity filters tab. 

problem does not occur with passive- & active provider chests since they only have one tab. 

example blueprint:
`0eNq1lNGOgyAQRf9lnjFRa7cpv7JpDOrokii4MNiaxn9f0Idt2pq02fXJAJc794xkrlC0DnsjFQG/giy1ssA/r2Blo0Qb9mjsEThIwg4YKNHNK1VLJWmMyi+0FImS5IBRb/QgKzQwMa+o8AI8mdi7Zr2wdsUtnU4MUJEkiUvOeTHmynWFV/JkzdSSNqJBX7TX1l/XKsTxltGewQg8nossV3KLRFI1NkgMdnrA3PmzltBglYfw/oiMQwbL7pLlvrJ1hSUx12JQahd6vI8ZdLoKOrz4trUj3PTqNIV23TGla0yFq2sveETabYZUCtPo6CyaPzLt1pgMfjv/fYqVbIfln71XlaFaZHSh6Zcuid/Hy15+2w+U6WaQdetk9Q//bv/qFHhgyzZj613XP4USFLUoLN1R+TEyzyB+M/8YDN5+TnvYxckxS7PDx3GafgBhH8zo`

source of blueprint (infinity buffer chest): 
![image](https://user-images.githubusercontent.com/29695655/68545984-9cfc0900-03d2-11ea-8d14-87a3a4a14f0f.png)

**Comment by raiguard** [comment] 2019-11-13 19:52
Huh... this is actually a bug in vanilla! I'll report it on the forum. Thank you!

**Comment by raiguard** [comment] 2019-11-13 20:30
Hmm, perhaps not, I tested it with some other mods that add infinity logistic chests and it doesn't happen there. Odd...

**Comment by raiguard** [comment] 2019-11-13 20:49
Aha! There's something screwy going on with infinity loaders and infinity wagons that is causing this. I'll look into it.

**Comment by Calibretto22** [comment] 2019-11-13 21:06
Thank you very much for maintaining this mod. Please write here if I can assist with testing or further explanation.

**Comment by raiguard** [comment] 2019-11-13 21:31
So, uno reverse card again! The issue is caused by infinity mode, but the issue itself is actually a vanilla problem! So I [created a bug report](https://forums.factorio.com/viewtopic.php?f=7&t=77957&p=466103#p466103) on the forums. We'll see what happens.

**Comment by raiguard** [comment] 2019-11-13 22:32
Woot, it's fixed for the next Factorio version! I'll close this once that comes out.

**Closed as completed** 2019-11-14 21:08 UTC
Labels: bug
